### ISSUE TITLE
MIDI parsing complete IRQ

### ISSUE THREAD

**Issue by anarkiwi** [anarkiwi/vessel#6]
Vessel should wait for a complete MIDI message to be in the buffer before triggering an IRQ.

**Comment by franticht** [comment]
Preferably this should also translate running status messages into full explicit messages — at least as an option. That way the MIDI IN parsing code on the C64 side could be kept simpler, with fewer checks and branches.

**Comment by anarkiwi** [comment]
First implementation in https://github.com/anarkiwi/vessel/pull/7 (needs to be made configurable).

**Comment by anarkiwi** [comment]
Configuration done in https://github.com/anarkiwi/vessel/pull/10.
